SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `accessCard` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `accessCard`;
-- --------------------------------------------------------

CREATE TABLE `accessCard` (
  `cardId` BIGINT NOT NULL AUTO_INCREMENT,
  `password` INT NOT NULL,
  `userId` BIGINT NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


